In [7]:
import keras
import pandas as pd
import matplotlib.pyplot as plt
from keras.datasets import fashion_mnist, cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
from functools import partial
from sklearn.model_selection import train_test_split
import numpy as np

## Loading data

First, we load in the data and split it into a train and test set. 

In [2]:
images = np.load('a2_data/images.npy')
labels = np.load('a2_data/labels.npy')

In [5]:
print(images[:2])

[[[135 130 139 ... 144 147 150]
  [130 124 131 ... 142 143 143]
  [135 141 149 ... 153 153 153]
  ...
  [ 62  74  99 ... 110 138 129]
  [ 79  96 123 ...  72  76  94]
  [ 95  97 111 ...  70  66  82]]

 [[128 140 147 ... 140 134 134]
  [142 141 160 ... 129 122 121]
  [138 144 147 ... 120 129 134]
  ...
  [ 69  65  69 ... 101  92  90]
  [ 70  78  91 ... 102  96  92]
  [ 74  96 117 ...  99  92  82]]]


In [8]:
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

## Definition of common-sense difference

The difference between the predicted time and actual time will be quantified using the 'common-sense' time. The function that calculates this time difference is shown below.

In [35]:
def common_sense(time1, time2):
    time1min = time1[0]*60 + time1[1]
    time2min = time2[0]*60 + time2[1]
    
    diff = abs(time1min - time2min)
    csdiff = min(diff, 12*60-diff)
    csdiffhr = np.array([int(csdiff/60), csdiff%60])
    
    return csdiff

print('Time 1: ', labels[500], '\nTime 2: ', labels[17500], '\nDifference in minutes: ', common_sense(labels[500], labels[17500]) )

Time 1:  [ 0 20] 
Time 2:  [11 40] 
Difference in minutes:  40


## Regression

## Classification

## Multi-head models

## Optimizing final model